################################################################################
###                                                                          ###
### Created by Martin Genet                                                  ###
###                                                                          ###
### École Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################

name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
  - fenics=2019.1.0
  - git
  - gnuplot
  - itkwidgets=0.32.6
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jupyterlab
  - matplotlib
  - numpy=1.21.5 # MG20221220: later numpy versions seem incompatible with itkwidgets 0.32
  - python
  - vtk=9.0

  - pip
  - pip:
    - dolfin_mech
    - dolfin_warp
    - gmsh

variables:
  CPATH: /srv/conda/envs/notebook/include/vtk-9.0
