################################################################################
###                                                                          ###
### Created by Martin Genet                                                  ###
###                                                                          ###
### École Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################

name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy=1.23.1
  - scipy=1.9.0
 