################################################################################
###                                                                          ###
### Created by Martin Genet                                                  ###
###                                                                          ###
### École Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################

name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10
  # - mpi4py=3.1.3
  - numpy=1.23.1
  - scipy=1.9.0
  # - seaborn=0.13.0
  # - sympy=1.10.1

  # # Jupyter
  # - ipywidgets=8.0.1
  # - jupyter=1.0.0
  # - jupyter_contrib_nbextensions=0.7
  # - jupyter_nbextensions_configurator=0.6
  # - jupyterlab=3.5.0
  # - notebook=6.4.12

  # # Computing stuff
  # - fenics=2019.1.0
  # - gmsh=4.11
  # - meshio=5.3

  # # Plotting
  # - matplotlib=3.7

  # # PIP
  # - pip=22.2.2
  # - pip:
  #   - gmsh==4.11
  #   - meshio==5.3
  #   - git+https://gitlab.inria.fr/mgenet/dolfin_mech.git@main  # Link to the dolfin_mech repository
  #   - git+https://github.com/ManoochTayebi/micro_poro_structure_generator.git@main  # Link to the micro_poro_structure_generator repository

