# ################################################################################
# ###                                                                          ###
# ### Created by Mahdi Manoochehrtayebi                                        ###
# ###                                                                          ###
# ### École Polytechnique, Palaiseau, France                                   ###
# ###                                                                          ###
# ################################################################################

# name: Build, Test, and Publish

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build_and_test:
#     runs-on: ubuntu-latest
#     steps:
#       # Checkout repository
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       # Set up Miniconda
#       - name: Set up Miniconda
#         uses: conda-incubator/setup-miniconda@v2
#         with:
#           python-version: 3.10  # Match the Python version in environment.yml
#           auto-update-conda: true

#       # Debug Conda Environment Setup
#       - name: Debug Conda Environment Setup
#         run: |
#           echo "Conda info:"
#           conda info

#           echo "Conda list:"
#           conda list

#       # Create Conda environment
#       - name: Create Conda environment
#         run: |
#           conda env create -f .repo2docker/environment.yml
          
#           # List environments to confirm creation
#           echo "Conda environments:"
#           conda env list
          
#           # Activate the environment to confirm it works
#           source activate notebook
          
#           echo "Installed packages in the environment:"
#           conda list
          
#       # Install Jupyter Book
#       - name: Install Jupyter Book
#         run: pip install jupyter-book

#       # Build Jupyter Book
#       - name: Build Jupyter Book
#         run: jupyter-book build .

#       # Deploy to GitHub Pages
#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./_build/html

#   build_docker_image:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

#     steps:
#       # Checkout repository
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       # Install dependencies for Docker
#       - name: Install Docker dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
#           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
#           echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#           sudo apt-get update
#           sudo apt-get install -y docker-ce docker-ce-cli containerd.io

#       # Log in to GitHub Container Registry (GHCR)
#       - name: Log in to GHCR
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GHCR_TOKEN }}

#       # Build Docker image using Dockerfile in `.binder`
#       - name: Build Docker Image
#         run: docker build -f .binder/Dockerfile -t ghcr.io/${{ github.repository }}:latest .

#       # Push Docker image to GHCR
#       - name: Push Docker Image to GHCR
#         run: docker push ghcr.io/${{ github.repository }}:latest


name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Or any branch you want to trigger this workflow on
  pull_request:
    branches:
      - master  # This will also trigger for PRs to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest  # GitHub provides pre-configured Ubuntu runners

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Username from GitHub context
          password: ${{ secrets.GHCR_TOKEN }}  # GitHub token with write access to GHCR

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -f .binder/Dockerfile -t ghcr.io/${{ github.repository }}:latest .

      # Push Docker image to GitHub Container Registry
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
